class AppImages {
  static const String baseUrl = 'assets/images',
      settingsBaseUrl = 'assets/images/settings',
      appleIcon = '$baseUrl/apple.svg',
      wavesIcon = '$baseUrl/waves.svg',
      searchIcon = '$baseUrl/search.svg',
      calendarIcon1 = '$baseUrl/calendar1.svg',
      addDoc = '$baseUrl/adddoc.svg',
      emailIcon = '$baseUrl/email.svg',
      passwordSee = '$baseUrl/passwordsee.svg',
      passwordHide = '$baseUrl/passwordhide.svg',
      googleIcon = '$baseUrl/google.svg',
      welcomeBonus = '$baseUrl/welcomebonus.svg',
      homeIcon = '$baseUrl/home.svg',
      teacherIcon = '$baseUrl/teacher.svg',
      settingIcon = '$baseUrl/setting.svg',
      forwardIcon = '$baseUrl/forward.svg',
      forwardSmallIcon = '$baseUrl/forwardsmall.svg',
      walletIcon = '$baseUrl/wallet.svg',
      emailIcon1 = '$baseUrl/ic_email.svg',
      redBadgeIcon = '$baseUrl/redbadge.svg',
      tickBadgeIcon = '$baseUrl/tickbadge.svg',
      dollarIcon = '$baseUrl/dollar.svg',
      giftIcon = '$baseUrl/gift.svg',
      expertStartIcon = '$baseUrl/expertstart.svg',
      addImageIcon = '$baseUrl/addimage.svg',
      tickOutlinedIcon = '$baseUrl/tickoutlined.svg',
      tickDottedIcon = '$baseUrl/tickdotted.svg',
      tickSuccessIcon = '$baseUrl/ticksuccess.svg',
      rejectExpertIcon = '$baseUrl/rejectexpert.svg',
      shareLinkIcon = '$baseUrl/sharelink.svg',
      docIcon = '$baseUrl/doc.svg',
      closeIcon = '$baseUrl/close.svg',
      chatIcon1 = '$baseUrl/chat1.svg',
      callIcon = '$baseUrl/phone.svg',
      videoIcon = '$baseUrl/call.svg',
      stripeIcon = '$baseUrl/stripe.svg',
      paypalIcon = '$baseUrl/paypal.svg',
      bankIcon = '$baseUrl/bank.svg',
      iconLock = "$baseUrl/iconlock.svg",
      xmarkIcon = "$baseUrl/xmark.svg",
      splashBg = '$baseUrl/splash.png',
      hamburgerIcon = '$baseUrl/hamburger.svg',
      online = '$baseUrl/online.svg',

      //Settings
      chatIcon = '$settingsBaseUrl/chat.svg',
      deleteIcon = '$settingsBaseUrl/delete.svg',
      favIcon = '$settingsBaseUrl/fav.svg',
      privacyIcon = '$settingsBaseUrl/privacy.svg',
      profileIcon = '$settingsBaseUrl/profile.svg',
      supportIcon = '$settingsBaseUrl/support.svg',
      termsIcon = '$settingsBaseUrl/terms.svg',
      logoutIcon = '$settingsBaseUrl/logout.svg',
      lockIcon = '$settingsBaseUrl/lock.svg',
      bellIcon = '$settingsBaseUrl/bell.svg',
      editIcon = '$settingsBaseUrl/edit.svg',
      cancelRedIcon = '$settingsBaseUrl/cancelred.svg',
      calendarIcon = '$settingsBaseUrl/calendar.svg',
      cameraIcon = '$baseUrl/Vector.svg',
      iconSun = '$baseUrl/iconSun.svg',
      calender = '$baseUrl/calender.svg',
      contactSupport = '$baseUrl/contactSupport.svg';

  //onboarding

  static const siginImg = "$baseUrl/signinImage.png";
  static const onlineoffline = "$baseUrl/onlineoffline.svg";
  static const tickbadgeblack = "$baseUrl/tickbadgeblack.svg";
  static const profile = "$baseUrl/Profile.svg";
}
