// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu2OWBbu7hAh64GM9j6Ftd1D7hKBnuM5k',
    appId: '1:514128207933:web:1eb676e57785257a6dca54',
    messagingSenderId: '514128207933',
    projectId: 'recess-68407',
    authDomain: 'recess-68407.firebaseapp.com',
    storageBucket: 'recess-68407.appspot.com',
    measurementId: 'G-T2QH949G02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsOz_OI7MMZXiF4TEo4cAOJa9FLtFUjPw',
    appId: '1:514128207933:android:32cfaf821234e15e6dca54',
    messagingSenderId: '514128207933',
    projectId: 'recess-68407',
    storageBucket: 'recess-68407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA22R06J9qenxFB6H9xkuq3U1pjmVevaEY',
    appId: '1:514128207933:ios:ca1e56b14409fb586dca54',
    messagingSenderId: '514128207933',
    projectId: 'recess-68407',
    storageBucket: 'recess-68407.appspot.com',
    iosClientId: '514128207933-juvqeumj5lrjvba82fbr8mbbk11k66o1.apps.googleusercontent.com',
    iosBundleId: 'com.app.recess',
  );
}
